import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Container from '@/components/Container'
import { Button } from '@mui/material'
import styled from '@emotion/styled'


const inter = Inter({ subsets: ['latin'] })
// const CustomButton = styled(Button) ({
//   position: 'relative',
//   bottom: 200,
//   left: '50%',
//   transform: 'translateX(-50%)',
//   zIndex: 2
// })

export default function Home() {
  return (
    <>
      <Head>
        <title>Onboarding test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container/>
    </>
  )
}
